import { writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildNginxSecurityHeaderLines } from '../src/config/security-headers.ts'

const currentDir = dirname(fileURLToPath(import.meta.url))
const outputPath = resolve(
  currentDir,
  '../deploy/nginx/security-headers.conf.template',
)

const lines = [
  '# Generated by scripts/generate-nginx-security-headers.ts — do not edit manually.',
  '# Re-run: npm run generate:nginx-security-headers',
  '# Keep in sync with src/config/security-headers.ts',
  '',
  ...buildNginxSecurityHeaderLines(),
  '',
]

writeFileSync(outputPath, lines.join('\n'))
